# Backend configuration
backend:
  name: applch-backend
  image: docker.io/rkaeffer/codelab-gitops-backend:1.0.0
  containerPort: 8080
  host: lchartrain-backend.codelab.cloud-sp.eu
  service:
    port: 443
# frontend configuration
frontend:
  name: applch-frontend
  image: docker.io/rkaeffer/codelab-gitops-frontend:1.0.0
  containerPort: 4200
  host: lchartrain-frontend.codelab.cloud-sp.eu
  service:
    port: 443